services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_redmine
    volumes:
      - database:/var/lib/postgresql

  redmine:
    image: redmine
    environment:
      - REDMINE_DB_POTGRES=db
      - REDMINE_DB_PASSWORD=example
    ports:
      - 9999:3000
    depends_on:
      - db
    volumes:
      - files:/usr/src/redmine/files

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=goalkaev
    ports:
      - 8083:8080

volumes:
  database:
  files:
